/** One inventory for registration coverage, compatibility reporting and generated documentation. */
export interface Capability { name: string; kind: "tool" | "resource" | "template" | "prompt"; v1: "supported"; v2: "supported" | "unsupported" | "blocked"; reason?: string }
export const capabilities: readonly Capability[] = [
  { name: "opencode_job_get", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_job_cancel", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_project_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_project_init", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_project_current", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_setup", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_ask", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_reply", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_conversation", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_sessions_overview", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_context", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_wait", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_review_changes", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_provider_test", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_run", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_fire", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_check", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_status", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_tui_append_prompt", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_submit_prompt", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_clear_prompt", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_execute_command", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_show_toast", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_open_help", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_open_sessions", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_open_models", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tui_open_themes", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_question_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_question_reply", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_question_reject", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_job_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_job_input", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_find_text", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_find_file", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_find_symbol", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_file_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_file_read", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_file_status", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_message_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_message_get", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_message_send", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_message_send_async", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_command_execute", kind: "tool", v1: "supported", v2: "blocked", reason: "V2 2.0.6 command accepts no caller identifier and returns void; exact execution completion cannot be correlated safely." },
  { name: "opencode_shell_execute", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_create", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_get", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_delete", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_update", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_children", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_status", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_todo", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_session_init", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_session_abort", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_fork", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_share", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_session_unshare", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_session_diff", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_summarize", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_revert", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_unrevert", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_permission_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_permission", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_session_search", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_events_poll", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_health", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_provider_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_provider_models", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_provider_auth_methods", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_provider_oauth_authorize", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_provider_oauth_callback", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_auth_set", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_config_get", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_config_update", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_config_providers", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_path_get", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_vcs_info", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_instance_dispose", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_agent_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_command_list", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_lsp_status", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_formatter_status", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_mcp_status", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_mcp_add", kind: "tool", v1: "supported", v2: "supported" },
  { name: "opencode_tool_ids", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_tool_list", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "opencode_log", kind: "tool", v1: "supported", v2: "unsupported", reason: "No equivalent published V2 API; V1-only capability." },
  { name: "project-current", kind: "resource", v1: "supported", v2: "supported" },
  { name: "config", kind: "resource", v1: "supported", v2: "supported" },
  { name: "providers", kind: "resource", v1: "supported", v2: "supported" },
  { name: "agents", kind: "resource", v1: "supported", v2: "supported" },
  { name: "commands", kind: "resource", v1: "supported", v2: "supported" },
  { name: "health", kind: "resource", v1: "supported", v2: "supported" },
  { name: "vcs", kind: "resource", v1: "supported", v2: "supported" },
  { name: "sessions", kind: "resource", v1: "supported", v2: "supported" },
  { name: "mcp-servers", kind: "resource", v1: "supported", v2: "supported" },
  { name: "file-status", kind: "resource", v1: "supported", v2: "supported" },
  { name: "project-scoped", kind: "template", v1: "supported", v2: "supported" },
  { name: "sessions-scoped", kind: "template", v1: "supported", v2: "supported" },
  { name: "session-scoped", kind: "template", v1: "supported", v2: "supported" },
  { name: "session-messages-scoped", kind: "template", v1: "supported", v2: "supported" },
  { name: "opencode-code-review", kind: "prompt", v1: "supported", v2: "supported" },
  { name: "opencode-debug", kind: "prompt", v1: "supported", v2: "supported" },
  { name: "opencode-project-setup", kind: "prompt", v1: "supported", v2: "supported" },
  { name: "opencode-implement", kind: "prompt", v1: "supported", v2: "supported" },
  { name: "opencode-best-practices", kind: "prompt", v1: "supported", v2: "supported" },
  { name: "opencode-session-summary", kind: "prompt", v1: "supported", v2: "supported" },
 ];
export function capabilityFor(name: string) { return capabilities.find(capability => capability.name === name); }
export const v2UnsupportedTools = new Set(capabilities.filter(c => c.kind === "tool" && c.v2 === "unsupported").map(c => c.name));
